name: Build/release

on: 
  workflow_dispatch:
  push: 
    branches: 
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      
      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.25.1
      
      - name: Install Packages
        run: pnpm i --no-frozen-lockfile
      
      - name: Release on mac
        if: startsWith(matrix.os, 'macos')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pnpm run release-mac
      - name: Release on PC
        if: startsWith(matrix.os, 'windows')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          pnpm run release-win
          
      - name: Slack Notification on Success
        if: ${{success()}}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CUSTTEAM }}
          SLACK_PAYLOAD: '{"text":"A new Studio version is available!"}'
        uses: Ilshidur/action-slack@2.0.2
      
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_CUSTTEAM }}
          SLACK_PAYLOAD: '{"text":"Studio release has failed. See logs for more details."}'
        uses: Ilshidur/action-slack@2.0.2
